configure:
    cmake -B build -G Ninja -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang

build: configure
    cmake --build build
    glslangValidator shaders/default.vert
    glslangValidator shaders/default.frag

test: build
    ./build/test
